server:
  port: 8089
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: farhanTest

gym:
 swagger:
   dev-url: http://localhost:8089/swagger-ui/index.html
   prod-url: https://bezkoder-api.com         