server:
  port: 8089
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: farhanTest  
       
gym:
 openapi:
   dev-url: http://localhost:8080
   prod-url: https://gym-api.com            